config/routes.rb
Rails.application.routes.draw do
  get 'musica/index'
  resources :discos
  resources :cantantes do
    resources :discos
  end
  root 'musica#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cantante.rb
class Cantante < ApplicationRecord
  has_many :discos  
end

app/models/disco.rb
class Disco < ApplicationRecord
  belongs_to :cantante
  validates_presence_of :nombre, :caracteristica, :cantante_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cantantes_controller.rb
class CantantesController < ApplicationController
  def index
    @cantantes = Cantante.all
  end

  def create
    @cantante = Cantante.find(params[:cantante_id])
    @disco = @cantante.discos.create(cantante_params)
    redirect_to cantante_path(@cantante)
  end

  private
    def cantante_params
      params.require(:cantante).permit(:nombre, :caracteristica, :cantante_id)
    end

end

app/controllers/discos_controller.rb
class DiscosController < ApplicationController
  def index
    if params[:cantante_id]
      @discos = Cantante.find(params[:cantante_id].to_i).discos
    else
      @discos = Disco.all
    end
  end
  def show
    @disco = Disco.find(params[:id])
  end

  def new
    @disco = Disco.new
  end

  def edit
    @disco = Disco.find(params[:id])
  end

  def create
    @disco = Disco.new(disco_params)
    if @disco.save
      redirect_to @disco
    else
      render :new
    end
  end

  def update
    @disco = Disco.find(params[:id])
    if @disco.update(disco_params)
      redirect_to @disco
    else
        render 'edit'
    end
  end

 def destroy
   @disco = Disco.find(params[:id])
   @disco.destroy
   redirect_to discos_path
 end


  private
  def disco_params
    params.require(:disco).permit(:nombre, :caracteristica, :cantante_id)
  end
end

app/controllers/musica_controller.rb
class MusicaController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cantantes_helper.rb
module CantantesHelper
end

app/helpers/discos_helper.rb
module DiscosHelper
end

app/helpers/musica_helper.rb
module MusicaHelper
end

app/views/cantantes/index.html.erb
<h1>Lista de cantantes</h1>
<table class="table table-striped">
  <tr>
    <th>Nombre</th>
    <th>Caracteristica</th>
    <th>Consultar</th>
  </tr>

  <% @cantantes.each do |cantante| %>
    <tr>
      <td><%= cantante.nombre %></td>
      <td><%= cantante.caracteristica %></td>
      <td><%= link_to 'Discos', cantante_discos_url(cantante), class:'btn btn-primary'%></td>
    </tr>
  <% end %>
  </table>
  <tr>
  <th><%= link_to 'Regresar', musica_index_path, class:'btn btn-default'%></th></tr>

app/views/discos/_edit.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title"><%= title %></h4>
      </div>

      <%= form_for @disco,  remote: true do |f| %>
      <div class="modal-body">
      <div class="form-group">
          <%= f.label :nombre %>
          <%= f.text_field :nombre,  :class => 'form-control'%>
      </div>

      <div class="form-group">
          <%= f.label :caracteristica %>
          <%= f.text_area :caracteristica,  :class => 'form-control' %>
      </div>

      <div class="modal-footer">
          <%= f.submit 'Guardar', class:'btn btn-primary  btn-lg btn-block' %>
      </div>
<% end %>
    </div>
  </div>
</div>

app/views/discos/_new.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>

      <%= form_for @disco,  remote: true do |f| %>
      <div class="modal-body">
      <div class="form-group">
          <%= f.label "seleccione un cantante" %>
          <%= f.collection_select( :cantante_id,  Cantante.all, :id, :nombre, {:prompt => 'Lista de Cantantes'})   %>
          <!-- estuve tratando de darle el estilo a el collection_select sin embargo al agregar al final
          {:class => 'form-control'} como lo indica el metodo habia problema con el hash y no guardaba los
           datos -->
          <small  class="form-text text-muted"> Solo puede agregar discos a cantantes de la lista</small>
      </div>

      <div class="form-group">
          <%= f.label :nombre %>
          <%= f.text_field :nombre,  :class => 'form-control'%>
      </div>

      <div class="form-group">
          <%= f.label :caracteristica %>
          <%= f.text_area :caracteristica,  :class => 'form-control' %>
      </div>

      <div class="modal-footer">
          <%= f.submit 'Guardar', class:'btn btn-primary btn-lg btn-block' %>
      </div>
<% end %>
    </div>
  </div>
</div>

app/views/discos/_show.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title"><%= title %></h4>
      </div>

      <div class="modal-body">
      <div class="form-group">
        <strong>Nombre:</strong>
        <%= @disco.nombre %>
      </div>

      <div class="form-group">
        <strong>Caracteristica:</strong>
        <%= @disco.caracteristica %>
      </div>

      <div class="modal-footer">
        <%= link_to 'Regresar', cantante_path, class:'btn btn-default btn-lg btn-block'%>
      </div>
<% end %>
    </div>
  </div>
</div>

app/views/discos/edit.js.erb
$('<%= j render "edit", title: "Editar Disco" %>').modal();

app/views/discos/index.html.erb
<h1>Listando Discos</h1>
<table class="table table-striped">
  <tr>
    <th>Nombre</th>
    <th>Caracteristica</th>
    <th>Editar</th>
    <th>Eliminar</th>
  </tr>

  <% @discos.each do |disco| %>
    <tr>
      <!-- Los nombres de la lista de discos son linkeable y sustituye
      el metodo Actualizar del CRUD -->
      <td><%= link_to disco.nombre , disco_path(disco)  %></td>
      <td><%= disco.caracteristica %></td>
      <div class="btn-group">
      <td><%= link_to 'Editar',  edit_disco_path(disco), class:'btn btn-primary', remote: true %></td>
      <td><%= link_to 'Eliminar', disco_path(disco),
              class: 'btn btn-danger',
              method: :delete,
              data: { confirm: '¿Está seguro de eliminar el disco?' } %></td>
    </tr>

  <% end %>

  </div>
</table>
<tr>
  <th><%= link_to 'Menu Principal', musica_index_path, class:'btn btn-default'%></th>
  <td><%= link_to 'Nuevo', new_disco_path, class:'btn btn-primary' , remote: true%></td>
</tr>

app/views/discos/new.js.erb
$('<%= j render "new", title: "Agregar nuevo Disco" %>').modal();

app/views/discos/show.html.erb
<h1>Datos de Disco</h1>
<table class="table table-striped">
  <tr>
    <th>Nombre</th>
    <th>Caracteristica</th>
  </tr>

  <tr>
    <th><%= @disco.nombre %></th>
    <th><%= @disco.caracteristica %></th>
  </tr>
</table>
  <%= link_to 'Regresar', discos_path, class:'btn btn-primary'%>
  <%= link_to 'Menu Principal', musica_index_path, class:'btn btn-default'%>

app/views/discos/show.js.erb
$('<%= j render "show", title: "Ver Disco" %>').modal();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Coditranmutana</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('musica.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style> @import url('https://fonts.googleapis.com/css?family=Raleway:400,500i');</style>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/musica/index.html.erb
<h2>Aplicación de música de Coditramuntana</h2>
<h3><%= link_to 'Lista de Cantantes', controller: 'cantantes' %> |
<%= link_to 'Lista de Discos', discos_path %></h3>